
language: cpp

sudo: true

notifications:
  email:
    recipients:
      - scrgiorgio@gmail.com
    on_success: always
    on_failure: always 
   
matrix:

  include:

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: COMPILER=clang++ BUILD_TYPE=Release 

    - os: linux
      dist: trusty
      env: COMPILER=g++-4 BUILD_TYPE=Release 
      addons: 
        apt:
          packages: g++-4
          sources:
            - ubuntu-toolchain-r-test
      

install:

    # (linux) install linux dependencies
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        sudo apt-get -qy update
        sudo apt-get -qy install swig3.0 git cmake  libssl-dev libx11-xcb1 python3 python3-pip
        sudo apt-get install python3 python3-dev libasound2-dev libfreetype6-dev xorg-dev libglu1-mesa-dev python3-pip libldap2-dev
        sudo pip3 install numpy setuptools wheel
        sudo python3 -m pip install --upgrade pip setuptools wheel
      fi     
      
    # (linux) Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
        mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
        export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
      fi
      
    # (osx) brew install dependencies
    - | 
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then 
        brew install swig    
        brew upgrade python # from 2 -> 3
        pip3 install numpy setuptools wheel
        gem install xcpretty # this is to solve logs too long
      fi    
 
script:
    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir build && cd build
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then  
      	cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../   
      	cmake --build ./ --target all
      	sudo cmake --build ./ --target install
      fi    
      
    - | 
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then      
      	cmake -GXcode ../
      	cmake --build ./ --target ALL_BUILD --config $BUILD_TYPE
      	cmake --build ./ --target install   --config $BUILD_TYPE 
      fi          
    
