name: build-pyplasm
on: [push] 

env:
  PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }} 
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:

  cpython-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9' , '3.10', '3.11']
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2    
    - name: install cpython
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/cpython.windows.sh


  cpython-macos:
    runs-on: macos-11
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9' , '3.10', '3.11' ]
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2
    - name: install cpython
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/cpython.macos.sh
            
  cpython-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2
    - name: Compile cpython
      shell: bash
      run: |
          set -ex 
          docker run --rm -v ${PWD}:/home/pyplasm -w /home/pyplasm \
            -e PYTHON_VERSION=${{ matrix.python-version }}  \
            -e PYPI_USERNAME=${PYPI_USERNAME} -e PYPI_TOKEN=${PYPI_TOKEN} \
            visus/portable-linux-binaries_x86_64:4.1 bash ./scripts/cpython.ubuntu.sh


  conda-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2     
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/conda.windows.sh
           
  conda-macos:
    runs-on: macos-11
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9']
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/conda.macos.sh
                  
  conda-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2
    - name: Compile cpython
      shell: bash
      run: |
          set -ex    
          docker run --rm -v ${PWD}:/home/pyplasm -w /home/pyplasm \
            -e PYTHON_VERSION=${{ matrix.python-version }}  \
            -e ANACONDA_TOKEN=${ANACONDA_TOKEN} \
            visus/portable-linux-binaries_x86_64:4.1 bash ./scripts/conda.ubuntu.sh






