name: conda
on: [push] 

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:

  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2     
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/conda.windows.sh
           
  macos:
    runs-on: macos-11
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9']
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ex
           export PYTHON_VERSION=${{ matrix.python-version }}
           source ./scripts/conda.macos.sh
                  
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
    - name: git clone pyplasm
      uses: actions/checkout@v2
    - name: Compile cpython
      shell: bash
      run: |
          set -ex
          export PYTHON_VERSION=         
          docker run --rm -v ${PWD}:/home/pyplasm -w /home/pyplasm \
            -e PYTHON_VERSION=${{ matrix.python-version }}  \
            -e ANACONDA_TOKEN=${ANACONDA_TOKEN} \
            visus/portable-linux-binaries_x86_64:4.1 bash ./scripts/conda.ubuntu.sh






